name: ci.yml
on:
  push:
    branches: [master]
  pull_request:

permissions: read-all

jobs:
  build:
    strategy:
      matrix: 
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Build Installer
        if: ${{ runner.os == 'Windows' }}
        run: iscc vrc-get.iss
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ matrix.os }}
          path: |
            target/release/git-vrc*
            Output/*
