name: ci.yml
on:
  push:
    branches: [master]
  pull_request:

permissions: read-all

jobs:
  build:
    strategy:
      matrix: 
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: cargo build --release
      - name: Build Installer
        if: ${{ runner.os == 'Windows' }}
        run: iscc git-vrc.iss
      - name: Copy files for distribution
        shell: bash
        run:
          mkdir build
          cp target/release/git-vrc* build/ || true
          cp Output/* build/ || true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ matrix.os }}
          path: build
